eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8070/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: microservice-professeur
          uri: lb://MICROSERVICE-PROFESSEUR
          predicates:
            - Path=/professeur/**
          filters:
            - RewritePath=/professeur/(?<path>.*), /$\{path}

        - id: microservice-cours
          uri: lb://MICROSERVICE-COURS
          predicates:
            - Path=/cours/**
          filters:
            - RewritePath=/cours/(?<path>.*), /$\{path}

server:
  port: 8000
